# GitHub Actions Workflow for Friendly Society

name: CI

on:
  push:
    branches:
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots verify

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: '**/*.md'

  branch-policy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Enforce branch naming for agentic pushes
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/heads/feature/ ]]; then
            echo "Feature branch naming OK."
          elif [[ "$GITHUB_REF" == "refs/heads/develop" ]]; then
            echo "Develop branch push."
          else
            echo "Branch name not allowed for agentic push: $GITHUB_REF" && exit 1
          fi

# Notes:
# - Only feature/* and develop branches are allowed for agentic pushes.
# - main is protected and should only be updated via PR by HiL reviewers.
# - PRs to develop and main will trigger the workflow for validation.
